worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level35=Sacrifice"), "C", "Content/Talos/Levels/sc_level_pack/level35.wld", 35)
worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level36=Ukulele"), "TCS", "Content/Talos/Levels/sc_level_pack/level36.wld", 36)
worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level37=Mutual Support"), "CS", "Content/Talos/Levels/sc_level_pack/level37.wld", 37)
worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level38=Thief"), "FC", "Content/Talos/Levels/sc_level_pack/level38.wld", 38)
worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level39=Oxozone"), "T", "Content/Talos/Levels/sc_level_pack/level39.wld", 39)
worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level40=Shuffle(1,2,3,4,5,6)"), "FR", "Content/Talos/Levels/sc_level_pack/level40.wld", 40)
worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level41=Reflective Moments"), "R", "Content/Talos/Levels/sc_level_pack/level41.wld", 41)
worldGlobals.CreateLevel(TranslateString("TTRS:ScLevelPack.Level42=Hesitation Ⅳ"), "TF", "Content/Talos/Levels/sc_level_pack/level42.wld", 42)
