worldGlobals.CreateLevel("Break Jamming", "C", "Content/Talos/Levels/sc_level_pack/level1.wld", 1)
worldGlobals.CreateLevel("Halloween", "FC", "Content/Talos/Levels/sc_level_pack/level2.wld", 2)
worldGlobals.CreateLevel("Detour", "FC", "Content/Talos/Levels/sc_level_pack/level3.wld", 3)
worldGlobals.CreateLevel("Domino", "C", "Content/Talos/Levels/sc_level_pack/level4.wld", 4)
worldGlobals.CreateLevel("Dependency", "FC", "Content/Talos/Levels/sc_level_pack/level5.wld", 5)
worldGlobals.CreateLevel("Close the Door Behind You", "R", "Content/Talos/Levels/sc_level_pack/level6.wld", 6)
worldGlobals.CreateLevel("Two Colors, Two Doors", "R", "Content/Talos/Levels/sc_level_pack/level7.wld", 7)
worldGlobals.CreateLevel("Traffic", "R", "Content/Talos/Levels/sc_level_pack/level8.wld", 8)
worldGlobals.CreateLevel("Gap", "FCR", "Content/Talos/Levels/sc_level_pack/level9.wld", 9)
worldGlobals.CreateLevel("Suspend", "CR", "Content/Talos/Levels/sc_level_pack/level10.wld", 10)
worldGlobals.CreateLevel("Milky Way Lovers", "FCR", "Content/Talos/Levels/sc_level_pack/level11.wld", 11)
worldGlobals.CreateLevel("Apophi", "TFC", "Content/Talos/Levels/sc_level_pack/level12.wld", 12)
worldGlobals.CreateLevel("Twilight", "TC", "Content/Talos/Levels/sc_level_pack/level13.wld", 13)
worldGlobals.CreateLevel("Draw Back", "TR", "Content/Talos/Levels/sc_level_pack/level14.wld", 14)
worldGlobals.CreateLevel("Mitosis", "TFCR", "Content/Talos/Levels/sc_level_pack/level15.wld", 15)
worldGlobals.CreateLevel("Teeterboard", "TFCR", "Content/Talos/Levels/sc_level_pack/level16.wld", 16)
worldGlobals.CreateLevel("Poppy in Tears", "TCR", "Content/Talos/Levels/sc_level_pack/level17.wld", 17)
worldGlobals.CreateLevel("Portability", "TFCR", "Content/Talos/Levels/sc_level_pack/level18.wld", 18)
