RunHandled(
  WaitForever,
  OnEvery(Event(fan1.Deactivated)),
  function()
    fans1:Activate()
    Wait(Delay(0.1))
    fans1:Deactivate()
  end,
  OnEvery(Event(receiver.Reset)),
  function()
    if fan1:IsActive() then
      fans1:Activate()
      Wait(Delay(0.1))
      fans1:Deactivate()
    end
  end,
  OnEvery(Event(fan2.Deactivated)),
  function()
    fans2:Activate()
    fans3:Activate()
    Wait(Delay(0.1))
    fans2:Deactivate()
    fans3:Deactivate()
  end,
  OnEvery(Event(switch.Deactivated)),
  function()
    if fan2:IsActive() then
      fans3:Activate()
      Wait(Delay(0.1))
      fans3:Deactivate()
    end
  end
)
